---
title: "Code book"
author: "Alexey Kholodov"
date: "`r Sys.Date()`"
output: 
    pdf_document:
        toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The brief description of the source dataset

The original dataset (https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip) has following data:  
- x_train, y_train, subject_train  
- x_test, y_test, subject_test  
- activity labels  
- features.txt  

'x_train' and 'x_test' have measurements of signals from the accelerometer and gyroscope 3-axial raw signals of smartphone for 30 participants for 6 different activities. The data was preprocessed and divided onto training and test datasets. More detailed information is available in the CodeBook of the source dataset. 

The source dataset contain information for the following signals:

tBodyAcc-XYZ  
tGravityAcc-XYZ  
tBodyAccJerk-XYZ  
tBodyGyro-XYZ  
tBodyGyroJerk-XYZ  
tBodyAccMag  
tGravityAccMag  
tBodyAccJerkMag  
tBodyGyroMag  
tBodyGyroJerkMag  
fBodyAcc-XYZ  
fBodyAccJerk-XYZ  
fBodyGyro-XYZ  
fBodyAccMag  
fBodyAccJerkMag  
fBodyGyroMag  
fBodyGyroJerkMag  
-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.  

The set of variables that were estimated from these signals are: 

mean(): Mean value  
std(): Standard deviation  
mad(): Median absolute deviation   
max(): Largest value in array  
min(): Smallest value in array  
sma(): Signal magnitude area  
energy(): Energy measure. Sum of the squares divided by the number of values   
iqr(): Interquartile range  
entropy(): Signal entropy  
arCoeff(): Autorregresion coefficients with Burg order equal to 4  
correlation(): correlation coefficient between two signals  
maxInds(): index of the frequency component with largest magnitude  
meanFreq(): Weighted average of the frequency components to obtain a mean frequency  
skewness(): skewness of the frequency domain signal   
kurtosis(): kurtosis of the frequency domain signal   
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window  
angle(): Angle between to vectors  


Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:  

gravityMean  
tBodyAccMean  
tBodyAccJerkMean  
tBodyGyroMean  
tBodyGyroJerkMean  

The complete list of variables of each feature vector is available in 'features.txt' of the source dataset.


## Dataset 'fullDS.txt'

The 'fullDS.txt' is one of the outputs of 'run_analysis.R' script. The resulting dataset consist:

Subject ID  
Activity Label - descriptive activity name  
Means and standard deviations data from original (source) dataset for the following signals:  
    tBodyAcc-XYZ  
    tGravityAcc-XYZ  
    tBodyAccJerk-XYZ  
    tBodyGyro-XYZ  
    tBodyGyroJerk-XYZ  
    tBodyAccMag  
    tGravityAccMag  
    tBodyAccJerkMag  
    tBodyGyroMag  
    tBodyGyroJerkMag  
    fBodyAcc-XYZ  
    fBodyAccJerk-XYZ  
    fBodyGyro-XYZ  
    fBodyAccMag  
    fBodyAccJerkMag  
    fBodyGyroMag  
    fBodyGyroJerkMag  

-XYZ' above is used to denote 3-axial signals in the X, Y and Z directions.  



## Dataset 'tidyDS.txt'

The 'tidyDS.txt' is one of the outputs of 'run_analysis.R' script and represent the tidy dataset, which is a result of processing of 'fullDS.txt'. The resulting dataset consist:

Subject ID  
Activity Label - descriptive activity name  
The average of each following variables for each activity and each subject:  
    tBodyAcc-XYZ  
    tGravityAcc-XYZ  
    tBodyAccJerk-XYZ  
    tBodyGyro-XYZ  
    tBodyGyroJerk-XYZ  
    tBodyAccMag  
    tGravityAccMag  
    tBodyAccJerkMag  
    tBodyGyroMag  
    tBodyGyroJerkMag  
    fBodyAcc-XYZ  
    fBodyAccJerk-XYZ  
    fBodyGyro-XYZ  
    fBodyAccMag  
    fBodyAccJerkMag  
    fBodyGyroMag  
    fBodyGyroJerkMag  

-XYZ' above is used to denote 3-axial signals in the X, Y and Z directions.  


